checks:
  php: true

filter:
  paths:
    - "src/*"

build:
  image: default-bionic

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    environment:
      php:
        version: 8.0.11
        ini:
          "xdebug.mode": coverage

    phpunit:
      dependencies:
        override:
          - composer self-update
          - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
      tests:
        override:
          - command: "./vendor/bin/phpunit --coverage-clover ./coverage.xml"
            on_node: 1
            coverage:
              file: coverage.xml
              format: php-clover
